version: '3'

services:
  mysql:
    image: mysql:8.0.22
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: foobarfoobar
      MYSQL_DATABASE: food_oms_development
      MYSQL_USER: foo
      MYSQL_PASSWORD: bar
    volumes:
      - ./docker:/docker-entrypoint-initdb.d
