on: [push, pull_request]
name: test
jobs:
  verify:
    services:
      mysql:
        image: mysql:8.0.22
        env:
          MYSQL_ROOT_PASSWORD: foobarfoobar
          MYSQL_DATABASE: food_oms_test
          MYSQL_USER: foo
          MYSQL_PASSWORD: bar
        ports: ["3306:3306"]
    strategy:
      matrix:
        ruby-version: [2.5]
        os: [ubuntu-latest]
        bundle_version: [2.1.4]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - name: Install dependencies
        run: |
          gem install bundler -v ${{ matrix.bundle_version }}
          bundle config set path 'vendor/bundle'
          bundle install --jobs 4 --retry 3
      - name: Test using rspec
        env:
          DATABASE_NAME: 'food_oms_test'
          DATABASE_HOST: '127.0.0.1'
          DATABASE_PORT: '3306'
          DATABASE_USERNAME: 'foo'
          DATABASE_PASSWORD: 'bar'
          DATABASE_ROOT_USERNAME: 'root'
          DATABASE_ROOT_PASSWORD: 'foobarfoobar'
          APP_ENV: test
        run: |
          mysql -h$DATABASE_HOST -u$DATABASE_ROOT_USERNAME -P$DATABASE_PORT -p$DATABASE_ROOT_PASSWORD -D $DATABASE_NAME < docker/update_database_schema.sql
          bundle exec rspec -fd
